version: "3.8"

services:
  social-media-feed:
    build: ./
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_PASSWORD=qwerty
    # TODO volume для логов
  db:
    restart: always
    image: postgres:latest
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 6432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5
volumes:
  pg_data:
    # external: true
