env: "prod"
http_server:
  host: "0.0.0.0"
  port: "80"
  timeout: 4s
  idle_timeout: 60s
# TODO Доделать нормальное подключение
db:
  username: "postgres"
  host: "0.0.0.0"
  port: "5432"
  dbname: "postgres"
  sslmode: "disable"
