env: "prod"
# TODO Добавить SSL
http_server:
  host: "0.0.0.0"
  port: "80"
  timeout: 4s
  idle_timeout: 60s
grpc_server:
  host: "sso"
  port: "44044"
db:
  username: "postgres"
  host: "postgres"
  port: "5432"
  db_name: "postgres"
  sslmode: "disable"
